### ISSUE TITLE
expected sequence of length 27 at dim 1 (got 26)

### ISSUE THREAD

**Issue by 1054651112** [declare-lab/BBFN#3]
Hi. When I was running the code, I encountered a problem, and the error was reported as follows:

Traceback (most recent call last):
  File "main.py", line 214, in <module>
    solver.train_and_eval()
  File "/content/drive/MyDrive/BBFN-main/src/solver.py", line 266, in train_and_eval
    train(model, optimizer, criterion, criterion_d, None, None, None, None, None)
  File "/content/drive/MyDrive/BBFN-main/src/solver.py", line 123, in train
    for i_batch, batch_data in enumerate(self.train_loader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/content/drive/MyDrive/BBFN-main/src/data_loader.py", line 110, in collate_fn
    bert_sentences = torch.LongTensor([sample["input_ids"] for sample in bert_details])
ValueError: expected sequence of length 27 at dim 1 (got 26)

May I ask what caused it?

**Comment by Clement25** [comment]
Hi, I never encountered a problem like this. I guess this happens due to missing '[CLS]' head token in BERT input.

**Comment by 1054651112** [comment]
Thank you for your reply. It is caused by different versions of Transformer, which I have solved.
