### ISSUE TITLE
About UR_FUNNY dataset

### ISSUE THREAD

**Issue by 1054651112** [declare-lab/BBFN#4]
Hi, When I use the UR_FUNNY dataset, the error is as follows:

Traceback (most recent call last):
  File "main.py", line 166, in <module>
    train_loader = get_loader(hyp_params, train_config, shuffle=True)
  File "/content/drive/MyDrive/BBFN-main/src/data_loader.py", line 62, in get_loader
    dataset = MSADataset(config)
  File "/content/drive/MyDrive/BBFN-main/src/data_loader.py", line 27, in __init__
    dataset = UR_FUNNY(config)
  File "/content/drive/MyDrive/BBFN-main/src/create_dataset.py", line 481, in __init__
    words.append(word2id[np.array(word)])
TypeError: unhashable type: 'numpy.ndarray'

Could you give me some advice? Thank you very much!

**Comment by 1054651112** [comment]
I found that it seems to be the dataset problem. Have you ever encountered a similar problem?

**Comment by Clement25** [comment]
No I haven't. I found your code segment is different from the main branch. You can clone the main branch and try again.

**Comment by 1054651112** [comment]
Thanks a lot! I ran it again, but it still reported two errors:

Traceback (most recent call last):
  File "/content/drive/MyDrive/BBFN-main/src/create_dataset.py", line 415, in __init__
    self.train = load_pickle(DATA_PATH + '/train.pkl')
  File "/content/drive/MyDrive/BBFN-main/src/create_dataset.py", line 21, in load_pickle
    return pickle.load(f)
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 166, in <module>
    train_loader = get_loader(hyp_params, train_config, shuffle=True)
  File "/content/drive/MyDrive/BBFN-main/src/data_loader.py", line 61, in get_loader
    dataset = MSADataset(config)
  File "/content/drive/MyDrive/BBFN-main/src/data_loader.py", line 27, in __init__
    dataset = UR_FUNNY(config)
  File "/content/drive/MyDrive/BBFN-main/src/create_dataset.py", line 478, in __init__
    words.append(word2id[word])
TypeError: unhashable type: 'numpy.ndarray'

I can't solve this problem at the moment😫, could you share the preprocessed data of the UR_FUNNY?

**Comment by Clement25** [comment]
Could you please check what are the contents in the variable 'word'?

**Comment by 1054651112** [comment]
Thank you very much! I tried to modify it, and now it can be trained, but the log showed as follows:

Found video that doesn't bolong to any splits: XXX

And the performance isn't very well, the Accuracy is around 60.

**Comment by Clement25** [comment]
You need to add 'use_bert' option in command line to enable the BERT encoder, then you can tune the hyperparameters for better performance.
